name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  PLUGIN_NAME: logseq-expand-by-level

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Build
        id: build
        run: |
          pnpm install
          pnpm build
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json icon.png demo.gif ${{ env.PLUGIN_NAME }}
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            package.json
